apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "diarity-be.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.actuator.port }}
      targetPort: {{ .Values.actuator.port }}
      protocol: TCP
      name: actuator
  selector:
    {{- include "diarity-be.selectorLabels" . | nindent 4 }}
