jwt:
  secret: ENC(IugLvytQ9ESgcm9zL/0JBc0CNmUEeTTtks2S0Nf1lcLTSAV5TFXEveEBLoj0jz6QQdttSffzE1T3MCW7Mcktd9oPsxk3lU0de3xxQxjjGXJtyyzmLipKb6UWCM1ISjpL)
  expiration: 3600
  refreshExpiration: 604800

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(G49YLWnfGJfLQ6pfWnsEpO9/A0aNTR2yTb1j+GxqlyZdRPyMQC4S6tpEI1LrjgSYMsCkWRkk9nLEiGKq0rUw9VUU6QhaktI4S7Vqn6iCijtUxexjAvT9rfOE4CeqOIwu8e72H3VNN8AFVMM5kOCJXA==)
            client-secret: ENC(i2NotrTYxt513FkAR3xMJOBdSU5ctBJASP1QlKWTlxdpdgjWKKaap5WXG9146mLJvsHAaJrpCaYgz+s9js1rroOK09JuDMnqohMTkEtH8O0=)
            scope:
              - email
              - profile
              - openid