spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 100
        order_inserts: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/auth/login/google/callback
            client-id: ENC(G49YLWnfGJfLQ6pfWnsEpO9/A0aNTR2yTb1j+GxqlyZdRPyMQC4S6tpEI1LrjgSYMsCkWRkk9nLEiGKq0rUw9VUU6QhaktI4S7Vqn6iCijtUxexjAvT9rfOE4CeqOIwu8e72H3VNN8AFVMM5kOCJXA==)
            client-secret: ENC(i2NotrTYxt513FkAR3xMJOBdSU5ctBJASP1QlKWTlxdpdgjWKKaap5WXG9146mLJvsHAaJrpCaYgz+s9js1rroOK09JuDMnqohMTkEtH8O0=)
            scope:
              - email
              - profile
              - openid

redirect-after-login: http://localhost:3000
