spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
        batch_size: 100
        order_inserts: true
        show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/diarity
    username: admin
    password: admin
