spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/dev
    baseline-on-migrate: true
    baseline-version: 1.0.0
    url: ENC(1iJnjtP3+zwsxsVN+/chlN/4yR8vUUJ/wPG53guGg0GNJRhgAiBygEZzmsQBFT0rhdX3/YwbuATlVqkNDnIemSh/X7JaAO9zAHybaHEv5E0=)
    user: ENC(TwJf8ipc9jjUbnaV+/J95gvH+sPS+JvMfr3uGhDB8gy61ksIsLykfDJVEeg2n6Sh)
    password: ENC(/SXZTHWDktYfpTm5yUqGOujbzoPhFreIaaFsD50WlFPPmFF9O8tJt4X3Hf36WcXOTQhftA3yzFMaKiIPgOKFYw==)
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
        batch_size: 100
        order_inserts: true
        show_sql: true
  datasource:
    url: ENC(1iJnjtP3+zwsxsVN+/chlN/4yR8vUUJ/wPG53guGg0GNJRhgAiBygEZzmsQBFT0rhdX3/YwbuATlVqkNDnIemSh/X7JaAO9zAHybaHEv5E0=)
    username: ENC(TwJf8ipc9jjUbnaV+/J95gvH+sPS+JvMfr3uGhDB8gy61ksIsLykfDJVEeg2n6Sh)
    password: ENC(/SXZTHWDktYfpTm5yUqGOujbzoPhFreIaaFsD50WlFPPmFF9O8tJt4X3Hf36WcXOTQhftA3yzFMaKiIPgOKFYw==)

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://dev-api.diarity.me/auth/login/google/callback

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

redirect-after-login: https://dev.diarity.me
