spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
        batch_size: 100
        order_inserts: true
        show_sql: true
  datasource:
    url: ENC(v2XdSPe61e7UpkEh0SzRxu8CZ/+nxkO6vgyfVE/n0HCQlj2piY7K9bhn7BX+9QROGdL2m87bW2DU7LPKK9567xZs9NEGOp31evsG8vZqYEcLetRwo5q7eCuBGAWSt0I4)
    username: ENC(F8CjMrkVIWTO0S+xeYPbQRiiL8Q9bQ3vfkOOAEQT/kNMwwuFW5NER66exEHscSPq)
    password: ENC(FEgU6lS3LcNq7apDb0Y00GZqn2Io6n+n4nWxc3kXVPIIiUeCKweDo5lCzL3+fLgejx8rSOysjCQWTZtrg8esoV/9TSAy4fovT1krLBIdAu9rm+wNVtknpfNmA3xTl7yX)
