name: CD for Spring Boot

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SERVER_USER:
        required: true
      SERVER_HOST:
        required: true
      SERVER_PORT:
        required: true
      HARBOR_USERNAME:
        required: true
      HARBOR_PASSWORD:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      JASYPT_ENCRYPTOR_PASSWORD:
        required: true
    inputs:
      APP_NAME:
        required: true
        type: string
      APP_PATH:
        required: true
        type: string

jobs:
  deploy:
    permissions:
      contents: read
      actions: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read version from build.gradle
        id: gradle_version
        run: |
          VERSION=$(grep "^version" build.gradle | sed 's/version[ =]*//;s/"//g')
          echo "VERSION_TAG=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Harbor Registry
        uses: docker/login-action@v3
        with:
          registry: altairharbor.duckdns.org
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push
        env:
          APP_NAME: ${{ inputs.APP_NAME }}
          VERSION_TAG: ${{ steps.gradle_version.outputs.VERSION_TAG }}
        run: |
          docker buildx build \
            --push \
            -t altairharbor.duckdns.org/diarity-be/${APP_NAME}:${VERSION_TAG} \
            .

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            export VERSION_TAG=${{ steps.gradle_version.outputs.VERSION_TAG }}
            export APP_NAME=${{ inputs.APP_NAME }}
            export APP_PATH=${{ inputs.APP_PATH }}
            docker login altairharbor.duckdns.org -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}
            docker pull altairharbor.duckdns.org/diarity-be/$APP_NAME:VERSION_TAG
            docker stop $APP_NAME || true
            docker rm $APP_NAME || true
            docker run -d \
              --name $APP_NAME \
              --restart always \
              -p 8080:8080 \
              -e JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }} \
              -e SPRING_PROFILES_ACTIVE=${{ inputs.VERSION_TAG }} \
              altairharbor.duckdns.org/diarity-be/$APP_NAME:VERSION_TAG
            docker system prune -f

      - name: Notify to Slack
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
